### ISSUE TITLE
Install Krita

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#10]
**Is your feature request related to a problem? Please describe.**
Not a problem but a request to have a photoshop alternative.

**Describe the solution you'd like**
Would like this installed:
https://krita.org

It's a good photoshop alternative

**Describe alternatives you've considered**
I put in tickets for other software to install

**Comment by aldmbmtl** [comment]
Holding on this. Workstations are getting quite large so I need to find a portable version that I can install on a share instead.
