### ISSUE TITLE
Shot name on pop out window

### ISSUE THREAD

**Issue by amandafrazier** [juno-fx/report#107]
**Is your feature request related to a problem? Please describe.**
For the pop out window when clicking on a version or a shot could we have the shot number included at the top. Could be difficult to make sure what shot you are putting a note under.

**Describe the solution you'd like**
Would just like for the shot number to be on pop out menu on the right as well, just helps for clarity :)

![shotname](https://github.com/juno-fx/report/assets/34635472/d44c87a0-dfdd-4aa4-a347-510b0022cca5)

**Comment by aldmbmtl** [comment]
This is done
