### ISSUE TITLE
Notification for notes on tasked versions

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#109]
Is your feature request related to a problem? Please describe.
It'd be great to get custom notifications in our box of the notes just on the shots we're assigned too.

Describe the solution you'd like
We have that total notes text, ideally we could click that and a side window slides over for the notes on the shots we're assigned too.

Describe alternatives you've considered

Additional context

**Comment by aldmbmtl** [comment]
I actually have a block of code that does this in Hubble, it just isn't turned on. I didn't get to test it enough so I just disabled it for now. I can look at this.

**Comment by aldmbmtl** [comment]
This has been added :)
