### ISSUE TITLE
Backdrops group with shots

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#110]
**Is your feature request related to a problem? Please describe.**
Love the new backdrop stuff. Would be great if you're importing a few other shots in your script.
**Describe the solution you'd like**
A new backdrop with the shot and color are kind of grouped together. 

**Describe alternatives you've considered**

**Additional context**

**Comment by skeleturtle** [comment]
Sub backdrops are on my to do list. I can definitely look into this.

Would you like the sub backdrops within the import backdrop to be grouped just by the shots, or would you like it to be shot/task based? So a backdrop for say 010_Ingest, and another for 010_Roto?

**Comment by lamepennies** [comment]
I like your last example but maybe we also ask Alvah and Costa

**Comment by skeleturtle** [comment]
Set up shot and task backdrops with unique colors per task that are consistent.

**Comment by aldmbmtl** [comment]
This is done I think?

**Comment by skeleturtle** [comment]
> This is done I think?

We currently aren't going with any sub task/shot backdrops, but I believe that maybe was removed on purposes and just utilizing a generic import backdrop? I can't totally recall, we also implemented batch imports with auto contactsheet creation. Which maybe was part of the reason?

@lamepennies can you confirm you are happy with the current import backdrop set up?
