### ISSUE TITLE
Update QC Tool

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#111]
**Is your feature request related to a problem? Please describe.**
Small issue with the QC tool where the grid is on the b input and not the a. Here's an update. You'll need to relink the exr in the group for the path on the network.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[qc_tool.zip](https://github.com/juno-fx/report/files/12064950/qc_tool.zip)

**Comment by aldmbmtl** [comment]
I can publish this one I am back home

**Comment by lamepennies** [comment]
I think I published last year.

**Comment by aldmbmtl** [comment]
This is done
