### ISSUE TITLE
Note Type Seperation?

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#112]
**Is your feature request related to a problem? Please describe.**
I think we should split version notes to only be allowed on the tasks and client notes on the shot area itself. Right now we can give notes kind of anywhere and I worry something might get lost if we're checking two different areas. I can better explain in the meeting this week but I figured just something to separate things better.

**Describe the solution you'd like**
Notes on shots would be locked to certain user groups and notes on versions were open to everyone. Notes on versions would be from QC and Notes on the shot level would be client notes or one day, overall internal review notes that has a collaborative effort on the shot. Then we'd split specific notes by task. 

MAYBE, even in the note area, you can add splits for specific tasks and you can save notes all at once versus putting a note on each task. 
**Describe alternatives you've considered**

**Additional context**

**Comment by lamepennies** [comment]
OR maybe, based on note type, this is better sorted.

**Comment by aldmbmtl** [comment]
We can discuss it. I think I know where you are going with it though. We will need to document and define the workflow first I think before we start coding it though.

**Comment by aldmbmtl** [comment]
This is in the new hubble now :)
