### ISSUE TITLE
Show shot/task on note pane

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#113]
**Is your feature request related to a problem? Please describe.**
It'd be great to see what shot you're about to leave a note on in the note pane. Even adding a highlight on the row could help too.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Screen Shot 2023-07-16 at 5 00 35 PM](https://github.com/juno-fx/report/assets/84925743/69b5db85-3df1-4de3-838c-358365648add)

**Comment by aldmbmtl** [comment]
Yea, we are also going to add the full path so you know what the path is to the task.

**Comment by aldmbmtl** [comment]
This is also related to this ticket

https://github.com/juno-fx/report/issues/107

**Comment by skeleturtle** [comment]
Looking at hubble, it appears this is still needed. Can we get a status?

**Comment by aldmbmtl** [comment]
This is done
