### ISSUE TITLE
Bulk Importer Contact Sheet - Add shot names 

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#114]
**Is your feature request related to a problem? Please describe.**
Testing out the bulk importer, works great. Any chance you can add shot names so we can see it in the contact sheet. Or the option to disable the texts in the contact sheet?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skeleturtle** [comment]
![image](https://github.com/juno-fx/report/assets/76455095/969fc66f-70a2-481d-9e02-1f12720ba30b)
![image](https://github.com/juno-fx/report/assets/76455095/9947cb93-9d12-40ea-8546-d1967a783504)


Just confirming I understand, is this kind of what you are looking for? I could group contact sheet with text nodes for each input generated during import, and connect the inputs into the text nodes which would then overlay the shot code. While also adding a control knob that when checked would disable all the text nodes in the group?

If i'm misunderstanding let me know, and we can maybe jump on a quick call.

**Comment by lamepennies** [comment]
Yeah exactly that. Just so we can see what shit is what versus having to zoom into the reads.

**Comment by skeleturtle** [comment]
Batch importer updated and includes a contact sheet option which will include the shot name and task its coming from
