### ISSUE TITLE
Bulk Importer Plates Reversed Order

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#115]
**Describe the bug**
The plates come in fine but they are reversed so 090 is first all the way down to 010
**To Reproduce**
Bulk import a sequence and you'll see

**Expected behavior**
Shots should come in order 010, 020, 030...

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**

**Comment by skeleturtle** [comment]
now sorting our children during batch import by code, This should resolve this issue. Ran a test on two sequences,1 which had quite a few shots and it looks to be working.
