### ISSUE TITLE
My tasks is slow to load

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#117]
**Describe the bug**
My tasks is slow to load. 
**To Reproduce**
I go to my tasks page, click around, then come back and it doens't refresh well. I have to go to the prod page and back before it'll be visible. 

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**

**Comment by aldmbmtl** [comment]
This is something I am actively trying to solve. Locally it runs quite quickly but the larger dataset on Dan drags it down. I am thinking about dynamically loading instead of loading them all in bulk.

**Comment by aldmbmtl** [comment]
This is fixed on the latest builds
