### ISSUE TITLE
Cleta taking over 2 minutes to launch 

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#119]
**Describe the bug**
Long launch for a machine

**To Reproduce**
Just launch a machine. It's taking usually like 2 minutes but this one is much longer. 

**Expected behavior**
Machine to launch in 2 minutes or less?

**Comment by aldmbmtl** [comment]
This is normal during peak hours. If AWS doesn't have the capacity, we are waiting in line. The GPU nodes are in very high demand, so if you want a node quicker, you can drop down to standard Artist machines instead of the GPU's.
