### ISSUE TITLE
Install RV

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#12]
**Is your feature request related to a problem? Please describe.**
Feature request...we need a player
**Describe the solution you'd like**
Please install: https://github.com/AcademySoftwareFoundation/OpenRV
**Describe alternatives you've considered**
Nothing like good ole RV
**Additional context**

**Comment by aldmbmtl** [comment]
I opened an issue with them to see if they can get us an apt package build. If not, we will probably revert to trying xstudio since they support Ubuntu.

https://github.com/AcademySoftwareFoundation/OpenRV/issues/12

**Comment by aldmbmtl** [comment]
Holding on this since xstudio seems much easier and better overall to deal with.
