### ISSUE TITLE
Render Presets

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#120]
**Is your feature request related to a problem? Please describe.**
Would love some render presets.

**Describe the solution you'd like**
If we select certain defaults, they'd have different settings. Probably need a list from the others but off the top of my head:

- SmartVectors - ALL Channels and potentially with DWAA Compression
- Roto - All Channels with auto DWAA
- Precomp - RGBA
- Matte - All Channels with auto DWAA

**Comment by aldmbmtl** [comment]
No, take what @lamepennies is saying. You can default based on his specs since we can just select smart vectors as a preset now.

**Comment by lamepennies** [comment]
We also can't have comp step as default RGBA as we usually delivery no alpha.

**Comment by skeleturtle** [comment]
So I started looking at doing the write node refactor and begin implementing these requests, but I need to take a moment to think of best practice. Currently I think we are getting two many different variables in different places that would be triggering changes to our write node output settings. These triggers could cause confusion, I'm going to take some time tonight thinking about the write node set up and the profiles overall.

**Comment by lamepennies** [comment]
At past studios, we've had a drop down to select what presets we want. I think I might have that write node if you want to take a look at it for reference.

**Comment by skeleturtle** [comment]
![image](https://github.com/juno-fx/report/assets/76455095/16d30393-e128-4101-8e62-16874bcae72e)
![image](https://github.com/juno-fx/report/assets/76455095/5968627f-4c19-47c7-814a-62069c347c53)

yup that is what we have, currently but I also have the precomp/slapcomp/matte options split out from those profiles. Which those simply trigger our descriptor and ensure they go to the correct location while leaving all currently selected settings alone.

We then also have an exr_compression setting now in hubble, which if set will provide us a project level default for compression.

We then have the request for potentially task specific settings which I'd rather now split out our profiles further into task specific type profiles.

I'll figure it out, I just want to ensure we don't have too many tiggers changing things

**Comment by lamepennies** [comment]
Here are some examples:

![Screen Shot 2023-07-21 at 9 19 34 AM](https://github.com/juno-fx/report/assets/84925743/706e5240-79ef-49f1-affd-ed0aae3df38e)
![Screen Shot 2023-07-21 at 9 20 01 AM](https://github.com/juno-fx/report/assets/84925743/dc5b00ef-e838-4852-bfa0-3ae63e083aa2)

**Comment by aldmbmtl** [comment]
This has been deployed and is working I think.
