### ISSUE TITLE
Save sequence contact sheets and update with latest

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#121]
**Is your feature request related to a problem? Please describe.**
It'd be great to save our contact sheet and be able to update with latest versions

**Describe the solution you'd like**
Ideally, you bring your sequence/contact sheet, save it, and have ability to update stuff selected to the latest version.

**Comment by skeleturtle** [comment]
This sounds more like we are looking for a smart read node? Where it would beable to recognize the context of the path being read in and alert the user when it's out of date, while also allowing the user to click a button to update to the latest version. This is on my list of to do's.

Please confirm if this is what you mean.

**Comment by lamepennies** [comment]
Yeah. Still need to save in v00 sequence but for sure a smart read

**Comment by skeleturtle** [comment]
this one is a bit old. I know we got the smart read node set up, but your last comment mentioning v0 sequences.  I'm still not 100% clear on the v00 sequence or if this is still needed? I understand v0's for delivery, but from an internal working perspective I am a bit confused. Let me know if there is anything still needed here.

**Comment by lamepennies** [comment]
I think we just need to set up v00 sequences and we should be able to save it there. Right now I just saved to my desktop

**Comment by skeleturtle** [comment]
- Look to auto create a V00 sequence as a Show Default. Users can still create seq/shots as needed
- Look to set up ability to save nuke scripts and other files into different contexts. So user can work in 1 shot and save it to another. Work around right now is to save into current shot, then open the other shot and import the nuke script.
- Add an auto update checkbox to our read node. Allowing users to have read nodes automatically update to the latest path if one is found.

**Comment by skeleturtle** [comment]
Merged onto our Edge jfx-nuke branch pending Release:
- Read node refactored to an on Create callback
- Auto update Checkbox added, where if True read nodes path will automatically update to the latest available publish when check status is run.
- onCreate callback will build any of our custom knobs that are missing. Meaning when user opens old script, old read nodes will get the new Auto Update knob 
- Added menu option in our zero > misc menu for users to batch set the state of the read nodes auto update knob.

**Comment by skeleturtle** [comment]
Latest updates merged into main, build running now
