### ISSUE TITLE
jfx_luna version.link broken in filemanager?

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#125]
I'm not sure exactly why, but at the moment it appears when using the verison.link from the version data I have stored on my item in jfx_widgets file manager. For whatever reason self.luna is retuning NoneType?

![image](https://github.com/juno-fx/report/assets/76455095/e8384ac3-d0a8-44b7-b6bf-10658f954c22)

**Comment by oneBlueFish** [comment]
What steps are you doing that throws this error?  I loaded up the file browser with the latest changes on the `edge` branch and it didn't raise any error.  I can chat with you tomorrow.

**Comment by skeleturtle** [comment]
this looks to have been resolved.
