### ISSUE TITLE
No such file or directory on new scene

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#126]
**Describe the bug**
When I went to create a new scene to start, it came in blank so I cleared nuke and tried to reopen it and I got this error.

**To Reproduce**
Create new scene

Using v1.0.12 of the pipeline

![Screen Shot 2023-07-20 at 10 54 24 AM](https://github.com/juno-fx/report/assets/84925743/494f9ef2-3e45-4593-a944-b919bde25726)

**Comment by lamepennies** [comment]
Follow up, tried to make another one and it came in blank too
![Screen Shot 2023-07-20 at 10 55 57 AM](https://github.com/juno-fx/report/assets/84925743/fec59fac-cc27-41a6-94ba-d6bd4ef64c46)

**Comment by lamepennies** [comment]
So closing nuke and launching a new one worked. I guess it didn't like me having one opening qcing stuff and then clearing it before I tried it.

**Comment by aldmbmtl** [comment]
Is this working now?

**Comment by lamepennies** [comment]
Yeah, just letting you know of the bug
