### ISSUE TITLE
Permission Denied while trying to publish

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#129]
Trying to publish a shot and I get this error.

![Screen Shot 2023-07-22 at 4 54 03 PM](https://github.com/juno-fx/report/assets/84925743/dbce3d1b-4765-4e99-98a4-a4e874eb7fd4)
![Screen Shot 2023-07-22 at 4 54 14 PM](https://github.com/juno-fx/report/assets/84925743/b394eeea-42b1-4b4a-bef2-9a2049888193)
After re-opening nuke, I see it still versioned up my script
![Screen Shot 2023-07-22 at 4 56 13 PM](https://github.com/juno-fx/report/assets/84925743/2b6081d5-24a2-4f2b-9409-e3a96104292a)

and was able to publish to v004

**Comment by aldmbmtl** [comment]
I think this is sorted out now with the mars/titan reboot
