### ISSUE TITLE
Can't publish 88J_0120

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#131]
Hello,
I can't seem to publish 88J_0120 

I've relaunched nuke and everything, still dice. I had this before and it versioned up to v05 but the work files are still in v04.

![Screen Shot 2023-07-24 at 12 47 19 PM](https://github.com/juno-fx/report/assets/84925743/89d52ffd-a4e4-46c6-8915-944562451da3)

**Comment by lamepennies** [comment]
Trying to load versions (v06)
![Screen Shot 2023-07-24 at 5 07 24 PM](https://github.com/juno-fx/report/assets/84925743/c9f429fe-3b1a-4023-9b2c-f3be2b93e2b5)

Then when i click on v05, nothing happens. 
V04 launches a nuke even though my script was empty and when I try to publish, same issue.
![Screen Shot 2023-07-24 at 5 10 19 PM](https://github.com/juno-fx/report/assets/84925743/f69fe954-c8e3-40f1-af7a-de694cb423fc)

**Comment by aldmbmtl** [comment]
@skeleturtle can you take a look at this as soon as you can? This one seems to be stuck now.

**Comment by skeleturtle** [comment]
Mars was down which caused the permission error since the directories weren't getting made. We rebooted mars and I got V4 published.

**Comment by aldmbmtl** [comment]
I'll open a ticket upstream for Mars to detect it Titan isn't ready.
