### ISSUE TITLE
File Manager Version Selection Error

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#132]
When selecting a version directly in the manager, I get this error.

![Screenshot_2023-07-27_00-44-00](https://github.com/juno-fx/report/assets/9037579/3f4a4be6-13c2-40a3-a7e9-21a6a1ccbcb3)

I also get this error from Luna. It looks like the filemanager is pass in None as the id it is looking for. This is killing the call on selection. I am not sure if this wasn't always going on and I just no noticed it?

![Screenshot_2023-07-27_00-47-28](https://github.com/juno-fx/report/assets/9037579/f4090e8d-b97f-4055-8360-d5147f2b9a9e)

**Comment by aldmbmtl** [comment]
There was a push made to drastically speed up Luna's query that pulls the projects data. That may have resulted in something missing on luna's end. Since this isn't being used much yet, just check to see if we broke something on our end. This doesn't seem to break anything else though.

https://github.com/juno-fx/luna/pull/66/files

This is the upstream change in Luna that I am holding in edge until we can verify that everything is stable downstream. We can rollback if needed but this the speed gains are worth running unless more things break.

**Comment by skeleturtle** [comment]
![image](https://github.com/juno-fx/report/assets/76455095/cd407943-f514-4fb5-8890-07c3a06277a3)


Issue is with the relatedOutMeta that is returned to us as a versions parent. This appears to be happening in jfx-luna when an outVersion is converted to a jfx-luna Version Class

if I get my version using luna.version_helper.get_version_by_id()  the parent outMeta looks to work correctly.

If I get my version from a task using task.work/deliveries/publishes. The outVersions parent outMeta works correclty

If  I take that version and convert it a jfx-luna Version class. it breaks.  version = Version(**outVersion)

**Comment by aldmbmtl** [comment]
This is fixed
