### ISSUE TITLE
Versioning local rendering

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#133]
When rendering locally in nuke a recent version and Publishing. Nuke will save a new version script and a thumbs up of the frame publishing will show as submitted. 

When checking the version in the production task, the version only shows the oldest publish but not the latest one.  Can we publish version by rendering either way, deadline or locally please...

**Comment by skeleturtle** [comment]
To confirm I'm understanding, are you saying when using the option in the juno write node to do a local render a Juno file wasn't created for the render? Currently publishing and rendering are not connected and are two separate actions. All our publishing does at the moment, is generate a new work version, and mark the previous version state as a Publish.

**Comment by lamepennies** [comment]
Is there a specific reason you want to render locally?

**Comment by skeleturtle** [comment]
I believe we are still waiting to get a datacase to fully understand the issue,  as there is still confusion on this one.

**Comment by skeleturtle** [comment]
I am going to close this ticket. It has been stale for a while, and we aren't clear on the issue. If there are still problems going on please re-open or create a new ticket with examples.
