### ISSUE TITLE
Crop before render

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#135]
I think we need a show crop tool or something bundled in the write node. Seeing a lot of bounding boxes not matching original resolution.

**Comment by skeleturtle** [comment]
I will do the following:
- If in a comp task on write node creation generate a crop node as the input. Set crop to shot resolution

**Comment by skeleturtle** [comment]
Repos Edge Branches Updated:
1. jfx-nuke
2. jfx-prod
3. jfx-luna 


Utilizing our context objects and envar to store users current Task Step. On write node creation if a user is in a 'Comp' Step a crop node will be created and set as the input for the write node.

This is pending release.

**Comment by skeleturtle** [comment]
Updates merged into main, builds running now
