### ISSUE TITLE
Can't bring in reads from a write node

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#136]
When I have a write, I can't seem to bring in the read by hitting R or the menu bar. It just brings up the directory. 
![Screen Shot 2023-08-01 at 6 36 50 PM](https://github.com/juno-fx/report/assets/84925743/2474c702-2e4f-4aa9-9110-ced6cef31208)

**Comment by aldmbmtl** [comment]
You need to press alt+r

**Comment by lamepennies** [comment]
Ah, we need to put all these hotkeys in the wiki.

**Comment by skeleturtle** [comment]
There should also be a button on the write node to create a read from the write
