### ISSUE TITLE
Job keeps losing render farm machine

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#137]
Hello,
I've noticed this job keeps losing nodes on the farm. I assume it's too heavy but thought you should know. I'll leave it up and you can kill it if you need. When I hop back into the shot I'll split it up but I guess we need a way to switch this to better nodes to get tougher renders out.

![Screen Shot 2023-08-02 at 5 27 06 PM](https://github.com/juno-fx/report/assets/84925743/0b993ad6-bdcf-4cce-b958-272e69e8150e)

**Comment by BosonHair** [comment]
Still happening when precomping around f1400.

**Comment by BosonHair** [comment]
I'm going to try and use a shorter frame range on one of the writes to see if this helps.

**Comment by BosonHair** [comment]
Ok, so that trim worked but tracking another issue. These frames load fine in my local nuke so I'm not sure why it won't render well on the farm. 
![Screen Shot 2023-08-06 at 7 59 37 PM](https://github.com/juno-fx/report/assets/139021271/15a24e0f-d773-4933-ab04-ddf0bac8a23a)

**Comment by BosonHair** [comment]
Trimmed that render too

**Comment by BosonHair** [comment]
So trimming all my renders. Sorry, I'm just live journaling. My therapist says it's supposed to help

**Comment by BosonHair** [comment]
![image](https://github.com/juno-fx/report/assets/139021271/37f5b458-754a-498a-b5a8-73b7eeaebc59)

So I think it's me. This is the longest shot I've done and for some reason I thought using a multiply would render correctly but that didn't so I trimmed everything to better match. Still might be an issue with the node power because some nodes I could view fine in nuke but whatever. I'll close this ticket.

**Comment by lamepennies** [comment]
So I think it's me. This is the longest shot I've done and for some reason I thought using a multiply would render correctly but that didn't so I trimmed everything to better match. Still might be an issue with the node power because some nodes I could view fine in nuke but whatever. I'll close this ticket.
