### ISSUE TITLE
Prod: Slate and Outputs from Hubble

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#150]
Need to grab all the slate and output configuration that is set in Hubble via a call to Luna.

**Comment by skeleturtle** [comment]
basic connection made in prod.

Overall context and ContextUtils really needs a refactor/rethought but thats definitely for another time.

**Comment by skeleturtle** [comment]
Also technically for the outputs/slates this is accessed via jfx-lunas get_project()
