### ISSUE TITLE
Pipe: Slate Gizmos

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#151]
Need to setup slate gizmos

**Comment by skeleturtle** [comment]
I've reached out to tony about getting the latest slate

**Comment by lamepennies** [comment]
This was ingested a while ago.

**Comment by skeleturtle** [comment]
> This was ingested a while ago.

We should have the initial setup in our pipe repo I still need to go through and set up all the logic and make needed adjustments. This will then be part of our publish process and in theory be connected into our delivery process by  @oneBlueFish 

Currently my prio is blender integration, but if that changes I can shift over to this.

**Comment by skeleturtle** [comment]
Slate gizmo is setup and pipe. We have another ticket going over our nuke templates setup and getting the slate integrated into publish: https://github.com/juno-fx/report/issues/191

Closing this ticket.
