### ISSUE TITLE
Pipe: Nuke Delivery Template

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#152]
Need to set these up. Talk to @lamepennies if you need to.

**Comment by skeleturtle** [comment]
A pipe branch and prod branch are in place with an initial set up. Still need the slate gizmo since we lost it. I reached out to Tony about this. The initial common output_template.nk script is very basic but is a starting point for getting outputs out.

**Comment by lamepennies** [comment]
Will try to send this weekend. I got busy this week, my bad

**Comment by lamepennies** [comment]
To reply, I sent an update to Dan and I noticed my previous versions are in pipe/nuke so I'm not sure where it was deleted from. I didn't have access to pipe to upload it. 

The font path needs to be updated as well as the burnin shot name.

**Comment by lamepennies** [comment]
Here's the script as well... 
[deliveries_template_v03.nk.zip](https://github.com/juno-fx/report/files/12449139/deliveries_template_v03.nk.zip)

**Comment by skeleturtle** [comment]
I have set up an initial delivery template and am utilizing our hubble settings for QT generation on publish
