### ISSUE TITLE
Status Update 

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#158]
Is your feature request related to a problem? Please describe.
Current status updates are not sync within the task/Production/Versions menu. Forcing the User to manually change the Status in multiple windows to reflect the correct stage of the task

Describe the solution you'd like
It will be ideal to have all the status to be sync so once a change is made is reflected on multiple menu for that task. The shot status itself should not change the status until all task are approved internally. 

A shot status update workflow will be ideal to automatically update when the following parameters are meet

	1. Shot is set by default ready to start when all task are set to ready to start as well 
	2. One a task changes the status to work in progress the shot status will automatically change the status to reflect work in progress as well
	3. The shot status will only update to pending client review only when all task are set to approved. Then at that point is means internally the shot is completed and ready to send to client. So the status will automatically reflect Pending client review 

Additional context

There is a ticket already based on this comment. I just added an additional request within, please refer to this ticket as well
https://github.com/juno-fx/report/issues/144

Image example below 
![image](https://github.com/juno-fx/report/assets/137588482/050b1354-f24c-45b6-8ac7-3b1865535a11)

**Comment by aldmbmtl** [comment]
This should be addressed in pipeline

@skeleturtle

**Comment by skeleturtle** [comment]
I'm having trouble fully understanding the ticket. But it also doesn't sound to me like a pipeline thing. Unless I begin working with hubble.

**Comment by aldmbmtl** [comment]
The status should be synced when pipeline does the publish on the version. So it should be a pipeline change I think no? I can see there being a need for this in the Hubble UI, but also the publish action in pipeline should also sync these statuses I would think.

**Comment by skeleturtle** [comment]
Pipeline can review shot status during publish, work, or delivery  and update the shot when conditions are met, but if a status is manually adjusted within hubble by production the same conditions should be followed. Which pipeline wouldn't have control over. So to me it make sense to have triggers within hubble

**Comment by aldmbmtl** [comment]
Fair point. We can probably solve this by adding versions to the mass edit selection and then adding a sync button.

**Comment by aldmbmtl** [comment]
This is actually done already
