### ISSUE TITLE
Note Pane per task 

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#159]
Is your feature request related to a problem? Please describe.
Currently you have to jump to multiple windows to add notes on various task when applicable. Making the User leave the window  to select the next task to open the window again an annotate once more  to keep communication clear and concise 

Describe the solution you'd like
It will be nice to have two features when creating notes

	1. A drop down menu per task available in that shot. So this way the USER can stay within the same window and provided feed in multiple areas of the shot without having to jump around back and fort
	2. Note link for multiple task. Having a way to link a single note to multiple task that may require or have the same feedback will cut down the repetition of typing the same thing x amount of time to keep all communication clear and concise  

Additional context
There is a ticket already based on this comment. I just added an additional request, please refer to this ticket as well
https://github.com/juno-fx/report/issues/113

![image](https://github.com/juno-fx/report/assets/137588482/2beb8c54-2c75-4462-9af1-70807c605a66)

**Comment by aldmbmtl** [comment]
This can be added

**Comment by aldmbmtl** [comment]
This is addressed in the new hubble
