### ISSUE TITLE
Need to store user first/last name

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#162]
I'd like us to store/track users first/last name in titan if possible.  This could be then used for rocket chat and other instances where we want to use peoples names rather than just usernames

**Comment by skeleturtle** [comment]
I believe you mentioned this being completed?

**Comment by aldmbmtl** [comment]
This is in KeyCloak. That updated isn't released yet

**Comment by skeleturtle** [comment]
Has this been released?

**Comment by skeleturtle** [comment]
@aldmbmtl Can we close? You mentioned this is in KeyCloak, are we all set?

**Comment by skeleturtle** [comment]
@aldmbmtl Following up can we close this now?

**Comment by aldmbmtl** [comment]
Keycloak didn't solve the issue. For now, Titan can't track this. We will probably need to use a different service.
