### ISSUE TITLE
Neat Video Reduce Noise

### ISSUE THREAD

**Issue by claudfx** [juno-fx/report#169]
**Is your feature request related to a problem? Please describe.**
For better denoise, industry standard.

**Describe the solution you'd like**
Buy a single license we can all share for neat video 
https://www.neatvideo.com/purchase

**Describe alternatives you've considered**
Using the Nuke Denoise but it gets blotchy and may not cut it for higher end clients.

**Additional context**
I like juno

**Comment by aldmbmtl** [comment]
Pending proper deployment. License is bought
