### ISSUE TITLE
Thumbnail Featurs

### ISSUE THREAD

**Issue by claudfx** [juno-fx/report#170]
**Is your feature request related to a problem? Please describe.**
No problem, just quality of life.

**Describe the solution you'd like**
Have thumbnails be resizable and as a bonus maybe play a gif OR mov preview pop up when clicked

**Describe alternatives you've considered**
kms

**Additional context**
helps get a better idea of the shot when reading the note assigned to it without having to open it up, especially if the thumbnail happens to be a frame where you can't really tell/remember what the shot is about.

**Comment by skeleturtle** [comment]
Once we start creating QTs on publish I'll look to add the ability of playing it in filemanager. Hubble would have to have its own set up.
