### ISSUE TITLE
Pixelfudger

### ISSUE THREAD

**Issue by claudfx** [juno-fx/report#172]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add http://www.pixelfudger.com/ to the side toolbar

**Describe alternatives you've considered**
What we have is fantastic, but this one has a few that are also great. 

**Additional context**
Some tool overlap with nstk but depending on the occasion I've found myself using whatever gets me there fastest.

**Comment by aldmbmtl** [comment]
Deployed
