### ISSUE TITLE
Stand Alone Publisher

### ISSUE THREAD

**Issue by claudfx** [juno-fx/report#173]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to publish shots without having to open the nuke script

**Describe alternatives you've considered**
Currently have to open the shots to publish, waiting between 2-3 shots at a time to avoid crashes. 

**Additional context**
In cases where we need to bulk re-render and re-publish shots, would be nice to have a stand alone publisher to go quicker.  Low prio quality of life thing.

**Comment by skeleturtle** [comment]
Standalone publish action has been added  and merged into our edge branch.

jfx-widgets/jfx-nuke edge branches are dependent on eachother as they include the larger actions refactoring. We will hold off on release until after the current show delivers to avoid any disruption/bugs.
