### ISSUE TITLE
Hubble Settings syntax highlighting

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#177]
We ran into an issue where I couldn't save an output setting in hubble and didn't know why.
Checking the console we found I was using incorrect syntax. This was a bit too hidden.

Can we please add syntax highlighting to hubble settings?

**Comment by aldmbmtl** [comment]
This is an external lib thing that MUI doesn't support out of the box. I will have to look into it later

**Comment by aldmbmtl** [comment]
This is in :)
