### ISSUE TITLE
Writte Node Delivery Default RGB

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#178]
Hello,

When creating a write node for delivery. Can we have the default channels to be set to RGB and remove the alpha please. 

That's all :)

**Comment by skeleturtle** [comment]
Until we have a proper delivery output set up, I would not have anyway of knowing if your current render is meant for delivery.

**Comment by skeleturtle** [comment]
I am going to close this ticket, as artist in the future will not be manually creating outputs for delivery, and as mentioned previously , there is no way of knowing what reasoning the artist is creating the write node. This along with the fact that future deliveries, client may request the alpha and to have things such as embedded mattes.
