### ISSUE TITLE
Hubble - Project Status flip  

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#179]
Hello,

When working in Hubble inside the Project menu. We have the status waterfall set as follow 

Sequence / Shot / Task # 

Can we had some automation so set when the shot status is set to **complete**, all the task(s) within the shot will inherit the same update, removing the need to manually change each one to match the shot status.

Cheers!

**Comment by skeleturtle** [comment]
https://github.com/juno-fx/report/issues/116

This ticket is related

**Comment by aldmbmtl** [comment]
This is done in the new hubble
