### ISSUE TITLE
Unable to connect to instance 404 page not found

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#18]
Launching an edge instance last night and now this morning results in me not being able to connect. It takes me to a page that just says 404 page not found.

**Comment by skeleturtle** [comment]
looks to happen on a standard developer instance as well

**Comment by aldmbmtl** [comment]
I made a ton of patches to Jupiter during the AWS tests which in turn changes Nexus (the local cluster) and broke its ingress controller. This is what gave you the 404. 

- I switched Nexus to nginx which is now a mirror of what we run on AWS
- I switched Nexus's Jupiter to its own branch so we can avoid this in the future
