### ISSUE TITLE
Additional status in My Task & Project

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#180]
Hello,

We have an array of status to represent a shot or task. To have even better communication on a status can we add the following:

* **NA** - In case a shot or task is not longer valid/needed/cancel
* **Hold** - IN case we need to pause production for a period of time

Thank you

**Comment by skeleturtle** [comment]
@Anthonygen1 a branch in luna has been created for this. When you are ready we can jump in. This is very quick and simple.

**Comment by aldmbmtl** [comment]
I can hit this one.

**Comment by aldmbmtl** [comment]
This is in
