### ISSUE TITLE
New Show Setup Requests

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#181]
When launching a new show please ensure each instance has the following added.

- Deadline Custom directory found in our DAN show

Show specific templates/scripts directories rather than us needing to use /pipe for show specific options
- shows/pipeline/templates 
- shows/pipeline/scripts

**Comment by skeleturtle** [comment]
Whats the status on this?

**Comment by aldmbmtl** [comment]
Is this replacing the need for `/pipe` entirely?

**Comment by skeleturtle** [comment]
> Is this replacing the need for `/pipe` entirely?

no sir, /pipe is our baseline/common location that all shows will access. It will house things beyond just templates/scripts but also our logos,fonts and other misc things we may need.

**Comment by aldmbmtl** [comment]
Those 2 directories are created and set to be open. Working on deadline now

**Comment by aldmbmtl** [comment]
![image](https://github.com/juno-fx/report/assets/9037579/8c3478dc-bf75-4822-8a44-71b8176ca909)

The Deadline env is also set.
