### ISSUE TITLE
Luna button broken

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#182]
There is a luna button on the bottom right next to the hubble button when using a machine.

1. When clicked the menu that shows up at the top center is hard to read and blends in with the rest of the background
2.  When selecting a task or whatever and trying to use it, it goes to a black page and says application error

**Comment by skeleturtle** [comment]
![image](https://github.com/juno-fx/report/assets/76455095/ade39308-5016-4b39-932a-bc47178ffe11)


This is still an issue

**Comment by skeleturtle** [comment]
Flagging that this is still broken

**Comment by aldmbmtl** [comment]
There is a render order issue in Hubble. I have been getting hit with it and I know where it is

**Comment by aldmbmtl** [comment]
This is no longer an issue with the new hubble
