### ISSUE TITLE
Password change/management for hubble

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#183]
As a user we really need the ability to manage our passwords for hubble. The fact I can't change my password, or click any sort of "Forgot my password" button is a bit much. If this is another whole security thing and we have to bug someone directly to send us a link or something, then we  give us a button that auto pings that person I guess....

**Comment by aldmbmtl** [comment]
@Anthonygen1 maybe this is something you can look into.

**Comment by Anthonygen1** [comment]
We do this for security reason I'm closing this issue. If we need to add it in just tell me.
