### ISSUE TITLE
Note Types

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#185]
My memory evades me and I don't have vpn to log into check but we need note types.

- Internal Feedback
- Internal Questions
- Client Feedback
- Roto/Paint Request
- Matchmove Request
- Vendor Feedback
This will be handy with packaging as well as staying organized. We'd probably also need filters to better sort these.

**Comment by skeleturtle** [comment]
Pull request is out for review with the following added:

INTERNAL_QUESTION
MM_REQUEST
ROTO_REQUEST
PAINT_REQUEST
VENDOR

**Comment by lamepennies** [comment]
Colors...hmmm

INTERNAL_QUESTION - #fffeb3
MM_REQUEST - #5e3c58
ROTO_REQUEST - #83adb5
PAINT_REQUEST - #2e4045
VENDOR - #c2f2d0
CLIENT - #fdf5c9
INTERNAL - #6FCB9F
CBB - #b7ded2

Maybe these?

**Comment by skeleturtle** [comment]
Updates have been pushed to git, and a pull request will be created shortly.

**Comment by skeleturtle** [comment]
Marked as pending release and shifted assignment to @aldmbmtl

**Comment by aldmbmtl** [comment]
Deployed on Edge
