### ISSUE TITLE
Bid days, due dates, and logged time in hubble

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#188]
At some point, we'll need to track time in Hubble as well as due dates. It'd also be nice to allow for color coding if we're getting close or over budget.

**Comment by skeleturtle** [comment]
Not my place, but Maybe this could be done automatically for the user it they log into a machine we would know time and project already.

**Comment by aldmbmtl** [comment]
Other studios have had that before where it does it on login. It ended up throwing off the time logs a ton. I would rather have them enter it manually. I will work on this next week.

**Comment by lamepennies** [comment]
What you suggested @skeleturtle would be great to log time for billing.

**Comment by aldmbmtl** [comment]
This is in progress in another epic
