### ISSUE TITLE
Launching Artist Machine Gives Me Forced Shutdown

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#189]
Hello,
I've tried to launch 2 workstations and I get this error each time, never seen this, what gives?

![CleanShot 2024-02-04 at 18 48 16@2x](https://github.com/juno-fx/report/assets/84925743/190b797a-7d3e-477d-827c-18036423ff17)

**Comment by aldmbmtl** [comment]
You aren't assigned to that show. So it has you blocked

**Comment by lamepennies** [comment]
Very good security, can I get added? Pretty please?

**Comment by aldmbmtl** [comment]
This is deployed. Reopen if you have issues
