### ISSUE TITLE
permission issues for juno snippit tool

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#193]
![image](https://github.com/juno-fx/report/assets/76455095/2c526450-8b5f-496b-a3d8-326b001b801c)

See attached, but we need to make sure all users have access to the snippit location so we can share nodes.

**Comment by aldmbmtl** [comment]
I will add this to the show setup job.

**Comment by aldmbmtl** [comment]
This is fixed in the latest build of CON now I think. Verify?

**Comment by skeleturtle** [comment]
This is working. Closing ticket.
