### ISSUE TITLE
Show Sandbox for Artists

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#201]
Hello,
Noticed when I was updating the template for Dan that we don't really have a shared space to save tools or anything. I did have permission to make a random folder in the show directory which should probably be fixed but we def need sandboxes for everyone on each show OR in a generic safe place.

**Comment by aldmbmtl** [comment]
I am not sure what you are referring to. Like just a dumping ground on the show storage? We don't really want that since artists will dump what they want there and then start using it in production.

**Comment by skeleturtle** [comment]
For our show specific templates/deadline scripts we do have the shows/pipeline/scripts, and shows/pipeline/templates directories. These should be set up now and should be open for artists (at some point just leads/supervisors) so we can create show specific templates without needing to go in and out of a cluster and deal with /pipe which houses our common templates/scripts/fonts etc which is completely locked down and would be the default for each show.

I had pointed @lamepennies to the wrong misc/template directory which he didn't have permissions to save to while we were working together to get the updated scripts handed back to each other.

Artist I know do like to create nuke toolsets/gizmos and what not. @aldmbmtl I could create a tool in nuke that would "publish" artist toolsets/gizmos/groups that can then be picked up in pipeline? Maybe I can have it go to the shows/pipeline area, and if a lead supervisor wanted that tool for all shows I can take it and get it integrated into /pipe?

**Comment by lamepennies** [comment]
This could also be a place to look dev shots that aren't necessarily tied to shots/tasks. I know we can't save stuff from the internet but that's also a good space for reference files. Then when the show is done, it's dumped.

**Comment by skeleturtle** [comment]
This should for the most part be all set. Closing.
