### ISSUE TITLE
all pipeline permission need updating

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#202]
All pipeline permissions during makeDirs needs updating. 

Status:
- Awaiting mode value

**Comment by aldmbmtl** [comment]
Is this still a thing?

**Comment by skeleturtle** [comment]
Most likely. There'd a lot of 077 or whatever going on and we've run into permission issues from time to time. Hard to 100% say where and what at the moment.

**Comment by aldmbmtl** [comment]
This seems good now.
