### ISSUE TITLE
Need better feedback when clicking buttons in Hubble

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#219]
We need better feed back when clicking buttons in hubble. Sometimes we click a button and I don't know if its actually working/registering the button click or not. I know some of this may have to do with the refresh rate or autoscaler,  and I have to refresh the page to see if the change took place or not. But having some sort of feedback that yes I clicked this button and something is happening would be nice.

**Comment by aldmbmtl** [comment]
This has been addressed in the newest build of hubble.
