### ISSUE TITLE
Workstation Launch "Terminated"

### ISSUE THREAD

**Issue by acosta9684** [juno-fx/report#22]
When launching a workstation, either  standard or edge I get the following termination in the workstastion

![image](https://user-images.githubusercontent.com/122050556/232340701-301d050e-88b0-45c8-a428-991f6fb0202e.png)

**Comment by aldmbmtl** [comment]
Your workstation is launched it looks like, give it a shot. If it works, feel free to close this.

**Comment by skeleturtle** [comment]
Can we close this?
