### ISSUE TITLE
Install KnobScripter

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#225]
This might be useful for people, not sure.

https://github.com/adrianpueyo/KnobScripter
https://adrianpueyo.com/knobscripter/

**Comment by aldmbmtl** [comment]
Just looked into this. We normally use our own IDE's for tool coding like this. We probably wouldn't use this. We can reopen this ticket though if you think artists would need it. We would still probably discourage against that too since those tools would be out of pipe from us.
