### ISSUE TITLE
Pycharm and black format settings

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#23]
When Pycharm gets deployed, can we ensure it's setting for line length is the correct length? Hardwrap should be set to 100 if I recall.

Black also when you run format isn't fixing the line lengths.

**Comment by skeleturtle** [comment]
Is this something thats possible, or should we close?

**Comment by aldmbmtl** [comment]
There is a way to do this with a blackrc file I think. This will take some research.

**Comment by aldmbmtl** [comment]
Did some research on this and it isn't actually possible the way we want it to work.
