### ISSUE TITLE
amplify graphql mutation err

### ISSUE THREAD

**Issue by Anthonygen1** [juno-fx/report#232]
I am experience an error when creating a model in my appsync api. I have 2 Models, an organization model and membership model, and there is a belongs to relationship between the 2 models. Organization is suppose to have many memberships and the membership is suppose to belong to the organization. 

I also have auth directives on both models which are the owner has CRUD permissions and if you are apart of the cognito user group that is set on both models you have read permissions. I am also using the cognito user pool as my auth method for the API calls. 

The error is when I create a membership model using the pre-generated mutations from aws amplify, It throws an error and DOES NOT return the organization it created the connection with and gives me a bunch of **_Cannot return null for non-nullable type etc._.** My steps to create this error are so and to create the model connection.

1. I create the organization model
2. I take the response from that API call and grab the organization ID 
3. I pass the organization ID to the createMembership Mutation 
4.  The API call for the createMembership mutation throws that error and doesnt return the organization data.

**The part that really confuses me**

If I then take the membership ID and run the pre-generated getMembership query. It **successfully** returns the membership model AND the organization model data too! 

I am unsure why the createMembership mutation throws those errors but yet the getMembership query gives me all the data for the organization. 

Now if I remove my auth directives and make those models public with an API key being the authMode, The createMembership mutation works. I am concluding something internally is clashing with the auth directives and this createMembership mutation, I have been digging into it trying to figure out why this is happening.

The work around is to just ignore the createMembership mutation because the model connection is successfully happening as you can see from when I run the getMembership query it returns the organization tied to it. And to just  move along and if I need the data from the response I can run another API call ( Specifically the getMembership query ) and use that to get my needed data to complete my process.

But i would really like to know why this mutation throws these errors. I believe it should not. Or at least I think it should not throw an error.

I have attached some screen shots for reference 

Also here are some links to the AWS Amplify documentation I have been using

[https://docs.amplify.aws/gen1/nextjs/build-a-backend/graphqlapi/data-modeling/#belongs-to-relationship](url)

[https://docs.amplify.aws/gen1/nextjs/build-a-backend/graphqlapi/customize-authorization-rules/#user-group-based-data-access](url)

![create_org_mutation_err](https://github.com/juno-fx/report/assets/29151988/153dad0e-9d8c-46df-b858-7e65f89f3c78)
![graphql_schema](https://github.com/juno-fx/report/assets/29151988/b96c7297-1d96-4ad2-858b-ab137624a503)
![get_membership](https://github.com/juno-fx/report/assets/29151988/20fee160-a536-40fa-9c0d-c554a57b1366)

**Comment by Anthonygen1** [comment]
I figured out a good workaround. I copied the pregenerated mutation that amplify generates for the client and edited the response that the mutation kicks back and removed the organization and user model from it so it does not throw an null error for that mutation response. 

closing since this is fixed for now

**Comment by mjnowen** [comment]
@aldmbmtl - can you post your error/issue to this Discord server? https://discord.gg/amplify

**Comment by mjnowen** [comment]
`@aws-amplify/cli@12.12.2` introduced a change in how we interact with the model. With this change, Amplify-generated resolvers did not allow fetching relational fields as a selection set of the mutation. The recommended pattern is to get the relational model ID and perform a get query against it with appropriate auth user.

For customers who relied on this behaviour, the CLI team introduced a new feature flag - #[subscriptionsInheritPrimaryAuth](https://docs.amplify.aws/gen1/javascript/tools/cli/reference/feature-flags/#subscriptionsInheritPrimaryAuth) in `@aws-amplify/cli@12.12.4`

Ref - https://github.com/aws-amplify/amplify-category-api/issues/2609
