### ISSUE TITLE
Launching SQM WS 

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#233]
Launching Artist WS was unable to deploy, VM Machine Kenneth 

Launched Artist GPU Ws, able to launch but deploying time was 2+ min, VM MAchine Dorothy

Usually WS do not take a over 2 minutes to be ready to deployment, noticed this being a bit odd when trying to create my on WS tonight

**Comment by aldmbmtl** [comment]
This is normal now with the newer workstations. They are far more robust and larger so it takes a little longer to spin up. The GPU one's ship with CUDA which makes them much larger as well. The other Artist WS is on a Spot capacity so it is just AWS not having capacity at the moment. This is expected.
