### ISSUE TITLE
Luna task assignment and creation 

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#237]
when trying to assign a task or create in Hubble. I was able to see my name added to it, but when refreshing the assigment will be gone

Current image is attempt 8 that finally worked.
![Screenshot 2024-08-10 11 11 34 PM](https://github.com/user-attachments/assets/edb150a4-8450-4f8a-9efe-ab00b303419f)

When making a new task, I am not able to do so
![Screenshot 2024-08-10 11 16 20 PM](https://github.com/user-attachments/assets/070ad5d2-e5b5-41c8-be11-ac01b4303ac9)

**Comment by alexander-costa** [comment]
in addition when new task is create screen freezes and i cant cancel the creation, I need to refresh the page

**Comment by aldmbmtl** [comment]
The screen freezing is a known issue in currently fighting in Hubble. 

The assignment I can't seem to recreate. Can you post the steps you're taking?

**Comment by aldmbmtl** [comment]
This is related to this issue as far as the lock up. I need more info on the other part of the issue.

https://github.com/juno-fx/hubble/issues/202

**Comment by aldmbmtl** [comment]
This is fixed now
