### ISSUE TITLE
Deadline fail to render locked on loop

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#238]
Submitted a job to deadline m starts rendering and fails and re-queued again and fails, continues the loop

job I'd  is in  the screen grab 

![Screenshot 2024-08-10 11 32 33 PM](https://github.com/user-attachments/assets/d35f0069-45cf-431d-b0eb-e6b92d0a0a95)
![Screenshot 2024-08-10 11 36 47 PM](https://github.com/user-attachments/assets/c1a87b68-8cd8-4a01-b3af-10bf5767faa0)

ERROR MESSAGE

![Screenshot 2024-08-10 11 38 11 PM](https://github.com/user-attachments/assets/526a2665-b055-485e-89c6-514741d98834)

**Comment by alexander-costa** [comment]
I suspended the job for you to try it and see

**Comment by ddesmond** [comment]
It looks like it cant find Nuke executable and thats the problem in this case.
Its probably apps "missing" on the node when its in render mode.

**Comment by aldmbmtl** [comment]
This is actually a deadline executable issue for sure. Apps is mounted, but deadline doesn't know where to look. Deadline is slated to be the first thing added to Terra as a service plugin. Maybe @ddesmond can help us pre populate the db once we get it moved over.

**Comment by ddesmond** [comment]
A quick fix would be to open Deadline monitor and go super admin, then check Plugin Nuke and paths for 14 that match the version to our apps one.

**Comment by ddesmond** [comment]
Yea we are running nuke 15, and deadline has 14 set in the error.
im in the workstation and will try to do a fix.

**Comment by ddesmond** [comment]
Updated Deadline plugin to our nuke version.
This Deadline10 version last Nuke supported version is 14, and we are now on 15.

We need to update our Deadline to 10.2 and update the plugin settings for our case

**Comment by ddesmond** [comment]
@alexander-costa if its working again, can we close the issue?
