### ISSUE TITLE
Artist WS Not launching 

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#239]
I am launching an artist WS and the wait time Is pass the 2 minute mark. I launched another artist ws and an  artist gpu one. Same result, I noticed I run into this issue when someone else has already one artist was running in Hubble. 

![Screenshot 2024-08-11 9 34 29 AM](https://github.com/user-attachments/assets/7eec4795-102b-4b76-930b-dcec6d36051d)

Forcing me to use the GPU every time

![Screenshot 2024-08-11 9 38 07 AM](https://github.com/user-attachments/assets/ea9ba8f6-8751-403a-8f12-81083a7a2a85)

**Comment by aldmbmtl** [comment]
Have you waited beyond that 2 min mark? I have launched multiple artist machines and it always works.

**Comment by aldmbmtl** [comment]
This is because we have a limit on the pool for only 2 artist stations at a time and it couldn't schedule you one since @skeleturtle and @lamepennies had workstations open at the same time. I can increase the workstation pool size and it should work now.
