### ISSUE TITLE
Need to discuss Default task implementation

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#24]
Hey guys,

I'm realizing we probably need to decide how we want to handle default task creation after a new a shot is created.
I'm setting up logic within the ingest app, but really it should probably be in jfx-luna or maybe luna? I'm not sure the best place.
But in theory, whether a shot is created via ingest or the user using hubble, a set of default tasks should probably be generated?
below are my thoughts about the default task naming. Currently on ingest I see some gross hardcoding for certain file types like 
luts, or if the step = comp.

Step: ingest
luts> I as just going to set it to 'lut'
plates > I was going to gather the plate 'element' and name the task after the element. BG01, FG01 etc.

Step: comp
main

Step: roto,paint
I was going to try again to grab the element from ingest. If it's not found I was just going to default it to the TaskType.value
 so it be Roto, Paint. same as the step. which I should probably do a .lower() on for consistency.

We could also skip creating a set of default tasks, and only create tasks for what's being ingested, and if a user choose to create a task.

Let me know what you guys think is best approach.

**Comment by skeleturtle** [comment]
This still need to be discussed with a plan of action defined.

**Comment by aldmbmtl** [comment]
This is a larger discussion. There is probably a need to define "workflows" and then a user can say like "create comp workflow" or something. Then it will trigger a workflow on the backend. It will require some work.

**Comment by aldmbmtl** [comment]
I think this is done now?

**Comment by aldmbmtl** [comment]
Closing for now since I am pretty sure this is complete.
