### ISSUE TITLE
Nuke - when bringing in a write, the crop/write aren't connecting to the tree

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#240]
When I make a write, the crop/write aren't connecting to the tree. I have to manually connect even though I had my last node selected

**Comment by aldmbmtl** [comment]
I don't think that's on our end. That may be a new change on the Nuke 15 side? We do provide "shift + z" as a Juno "node kisser" but the default ways the nodes are created are still all standard Nuke.

**Comment by lamepennies** [comment]
Oh, I thought it was because our custom node.

**Comment by lamepennies** [comment]
It even comes in offset from where you have your nodes selected.
