### ISSUE TITLE
Connecting Bug

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#243]
My machine locked me out and I lost my apps and review session. 

![Image](https://github.com/user-attachments/assets/a7822cbf-57c9-4ce6-b524-3def21cfa1e1)
![Image](https://github.com/user-attachments/assets/29f6dd24-1728-4901-a8da-4f027f9f0138)

**Comment by lamepennies** [comment]
Same issue on Melinda.

**Comment by lamepennies** [comment]
I had a brief snapshot of my memory and cpu at 100%

**Comment by lamepennies** [comment]
And with Julie, blank white screen.

![Image](https://github.com/user-attachments/assets/b89380d8-2c5b-4b85-af55-8c4fdd97dea1)

**Comment by lamepennies** [comment]
Ok, so I was able to connect to it but when I went out, it said it was still deploying for Julie

**Comment by aldmbmtl** [comment]
Looks like we are good for now. It was Spot Instances that are getting ripped out.
