### ISSUE TITLE
When logged in, screen goes white

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#248]
Just logged into SQM. My browser took about 30-45 to connect and was sent to a white screen. If I refresh it's correct.

**Comment by lamepennies** [comment]
Just to add, I'm using brave browser on a m2 mac studio

**Comment by aldmbmtl** [comment]
This is a known issue we are working on with the slower boot times from the CUDA containers. We are working on it.

**Comment by aldmbmtl** [comment]
Is this still happening?

**Comment by aldmbmtl** [comment]
This is patched with @ddesmond recent patch on Polaris :)
