### ISSUE TITLE
Off black squares in nuke viewer

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#255]
Noticing some off black squares in nuke when looking at stuff on black

![Image](https://github.com/user-attachments/assets/5d5e9892-d25b-45ef-b240-acbd86ae94e7)

**Comment by aldmbmtl** [comment]
I am not sure what you are referring to? Like the frame offset type of look?

**Comment by lamepennies** [comment]
If you look near the SL of the renders, you'll see off black blocks.
