### ISSUE TITLE
Need Basic Slate Nuke Gizmo

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#26]
We will need a basic slate gizmo which can be used for both rendering a slate image for exrs, and used in our delivery template nuke scripts.

I'd prefer the node could be named SLATE and any knobs that need to be updated dynamically via pipeline be labeled in appropriate and consistent manner.

**Comment by skeleturtle** [comment]
Slate has been started and is in pipe/common/nuke

**Comment by aldmbmtl** [comment]
@lamepennies can you help us out with this?

**Comment by skeleturtle** [comment]
https://github.com/juno-fx/luna/issues/44

linking a related ticket. We will want to be on the same page as to how we want to define our slates fields.

**Comment by aldmbmtl** [comment]
He can't see that repo.

**Comment by lamepennies** [comment]
Can you screenshot? I can update

**Comment by aldmbmtl** [comment]
That ticket is just referring to the project config for internal reference. I can't pull that ticket off of that repo and it is referencing source code that you wouldn't be able to see anyway. 

@skeleturtle can you give @lamepennies a list of knobs you need so he can build the gizmo based on that?

**Comment by skeleturtle** [comment]
@lamepennies @aldmbmtl 
![slate_node](https://github.com/juno-fx/report/assets/76455095/3ea70c7d-c3dd-41b1-8984-818d5c277dbf)
![image](https://github.com/juno-fx/report/assets/76455095/218e5d80-ed98-4df4-80d0-699b7b757347)

So I don't have an exact idea of what it is you guys want for the slate, and believe we need to get on the same page of what it is we are looking for. Looking at the current slate gizmo we do have I would say too many hardcoded knobs. With each potential field option being built into the node. See attached. This requires pipeline to assume/expect each of these knobs and passing in data as needed to each of them very specifically. It also means if client wanted any extra information we would be adding another knob for that data.

Personally I think most of this should be handled by our Hubble config, where a user can add whatever labels/values they need for the slate. Obviously the values need to be dynamic. Which for me I would say we set up the user appyling our tokens similar to the hubble strings/paths set up. We would also however want to set up a type of formatting the user can use that wouldn't be based on these tokens but essentially triggers to call for values within our DB. It could be something like {meta.Shot.metadata.timecode}. I in pipeline would then write the logic to make a DB calls to grab the current shots timecode from the metadata field.

With this set up, I would think we try and do a single multi line string knob. We would then have the slate node take take each key/value within the configuration and add a new line to this knob which then gets applied to our output image. We could have a few knobs for things that we always want such like a Name: {seq}_{shot}_{task}_v{version} and then dynamically generate whatever else we need based on the configuration.

Obviously this is probably a lot and a bit confusing so I'm happy to jump on a call at some point when we are all free but we should definitely draw up a plan of the work flow and how we want the slate to look and how we want it to be managed.

**Comment by aldmbmtl** [comment]
This has been deployed to Luna and is being setup in Hubble.

https://github.com/juno-fx/luna/issues/44
https://github.com/juno-fx/hubble/issues/89

**Comment by aldmbmtl** [comment]
Since this is deployed now, I am going to close this for now.
