### ISSUE TITLE
(Bug: Polaris) 

### ISSUE THREAD

**Issue by Eharper07** [juno-fx/report#260]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

Polaris

### URL in Hubble.

https://sqm.junovfx.com/viewer/jovita/

### Browser

Chrome Based

### Describe the bug

ComfyUI will not start due to not being able to load shared library libpython3.12.so.1.0

### To reproduce

launch terminal, jumped to ComfyuI directory, and tried to launch comfyui.sh

### Expected behavior

Expect to see ComfyUI actually launch.

### Screenshots

![image](https://github.com/user-attachments/assets/6be90972-8c7c-4e81-aeb3-7df689ed5cde)

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Does this block you from using Orion daily?

No

**Comment by aldmbmtl** [comment]
This is probably a thing that can be fixed with devbox

**Comment by ddesmond** [comment]
ima having a running python3.10, we are somehow missing python 3.12 and venv just keeps ignoring

**Comment by ddesmond** [comment]
![image](https://github.com/user-attachments/assets/5a94d21a-c06d-440f-b9b8-95f2db5e622e)

**Comment by aldmbmtl** [comment]
Looks like we are good on this one. Good job @ddesmond !
