### ISSUE TITLE
Give Me Embergen

### ISSUE THREAD

**Issue by Eharper07** [juno-fx/report#261]
### Dupe Check

- [X] I have [searched Juno's feature requests](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature+Request%22) and there are no duplicates

### Serivce this pertains to.

Luna

### URL in Hubble.

https://sqm.junovfx.com/project/

### Describe the solution you'd like?

Add Embergen to the list of installers 

https://jangafx.com/software/embergen/download

### How important is this feature to you?

2

**Comment by ddesmond** [comment]
![image](https://github.com/user-attachments/assets/6f7cba4e-54cd-4e04-adff-aa093c7831d9)
Its doing something, but we need to test this on the cluster. @Eharper07

**Comment by ddesmond** [comment]
ZO!
emrgen, liquigen and geogen can all be installed trough Terra.
Thou! They will launch and crash currently until we update Polaris.

**Comment by ddesmond** [comment]
Polaris is updated to run Embergen on GPU workstations.
I will close this issue as the software works, and will be perma on all cluster as from the next Terra plugins update.

**Comment by ddesmond** [comment]
![Screenshot 2024-09-14 at 08 34 29](https://github.com/user-attachments/assets/24199174-a4cf-4034-b5cf-7357d983a349)
![Screenshot 2024-09-14 at 08 52 30](https://github.com/user-attachments/assets/9fb2b7c1-81ef-4ba6
![Screenshot 2024-09-14 at 08 51 11](https://github.com/user-attachments/assets/f70c3277-1764-4e06-bcd0-faa9a627f7bb)
-a491-774cc992e8fe)
