### ISSUE TITLE
Screen Guard will lead to Kasm Error

### ISSUE THREAD

**Issue by Eharper07** [juno-fx/report#264]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

Polaris

### URL in Hubble.

https://ray.junovfx.com/viewer/elsa/

### Browser

Chrome Based

### Describe the bug

When in a review session, most times when screen guard activates, I will move the mouse and the connection breaks causing a Kasm error leading me to have to refresh the page.

### To reproduce

sit in review - wait for screen guard to appear - move mouse - Kasm error.

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Does this block you from using Orion daily?

No

**Comment by aldmbmtl** [comment]
This has been fixed in the latest Hubble updates :)
