### ISSUE TITLE
Creating note with empty description breaks service

### ISSUE THREAD

**Issue by dstein-dmfx** [juno-fx/report#265]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

Luna?

### URL in Hubble.

https://sqm.junovfx.com/home/

### Browser

Chrome Based

### Describe the bug

Creating a new note without editing the default description causes things to break and the service is not accessible.

### To reproduce

1. Click on Compose for a new note
2. Click on Create or whatever without adding any note body.
3. Something not good happens

### Expected behavior

Empty note created or warning that note needs to have body.

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Does this block you from using Orion daily?

No

**Comment by aldmbmtl** [comment]
Issue is solved. Waiting on merge
