### ISSUE TITLE
Deadline Batch Render Size

### ISSUE THREAD

**Issue by alvahangelrune** [juno-fx/report#266]
### Dupe Check

- [X] I have [searched Juno's feature requests](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature+Request%22) and there are no duplicates

### Serivce this pertains to.

Deadline

### URL in Hubble.

https://ray.junovfx.com/viewer/donna/

### Describe the solution you'd like?

Would be nice to be able to pick render batch sizes sent from Nuke to Deadline. Thanks! <3

### How important is this feature to you?

3

**Comment by aldmbmtl** [comment]
@skeleturtle

**Comment by skeleturtle** [comment]
Costa request for default chunksize = 25

Currently this is now dependent on Ticket https://github.com/juno-fx/terra/issues/28

**Comment by skeleturtle** [comment]
This is getting deployed..

Deadline submission via write node will offer user a chunksize field with a the defaults et to 25
