### ISSUE TITLE
(Feature Request: null) Master Hubble Page

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#271]
### Dupe Check

- [X] I have [searched Juno's feature requests](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3A%22Feature+Request%22) and there are no duplicates

### Serivce this pertains to.

null

### URL in Hubble.

https://ath.junovfx.com/home/

### Describe the solution you'd like?

I'm not sure if you're already working on this but I think we need a master hubble page as a launch pad for shows for artists as well as an easier way to add people to projects. Imagine a master hubble page that lists everyone in the company and you can add them easily as well as see full budgets, tasks, schedules, pretty much all data.

For artists or just to launch, you can see your projects and you click a button to launch a new tab for those projects.

Ideally, this could even integrate with Narro with bids, scheduling, and invoicing. Can discuss verbally if you'd like. 

### How important is this feature to you?

3

**Comment by aldmbmtl** [comment]
This is currently being worked on in Genesis. I will close this since we are already working on it.
