### ISSUE TITLE
(Terra Installers) Stardust Template not found

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#272]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

Firefox inside my VM

### URL in Hubble.

https://ath.junovfx.com/settings/titan/

### Browser

Chrome Based

### Describe the bug

Stardust firefox template not loading on ATH

### To reproduce

Launched a workstation and firefox loaded with the error

### Expected behavior

It to load fine. 

### Screenshots

![Screenshot 2024-10-01 at 11 18 57 AM](https://github.com/user-attachments/assets/05764c9b-23bc-4d2e-b145-c365df8b7751)

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Does this block you from using Orion daily?

No

**Comment by aldmbmtl** [comment]
@ddesmond this seems to be just on ATH. Not sure if there is a reason for it.

**Comment by ddesmond** [comment]
Stardust needs to be installed on the cluster, and you need PAT key to do that in the installer.
