### ISSUE TITLE
(Bug: null) Can't view uploaded files in Mars

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#274]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

Mars

### URL in Hubble.

https://ath.junovfx.com/io/

### Browser

Chrome Based

### Describe the bug

I uploaded a zip to Titan and I can't view the files in Mars. Not sure if it's because I reloaded my credentials or not trying to demo it. 

### To reproduce

Uploaded files to Titan
Refreshed credentials (to show Marie)
Refreshed page because it didn't connect
Refreshed connection 

### Expected behavior

I expect to see the zip there to download to the network

### Screenshots

![Screenshot 2024-10-03 at 9 11 29 PM](https://github.com/user-attachments/assets/fea3069f-efb2-4384-84f5-211baebd3167)
![Screenshot 2024-10-03 at 9 12 13 PM](https://github.com/user-attachments/assets/bbc7d177-045d-4ef3-bcc3-d6c7acce4f2c)

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Does this block you from using Orion daily?

No

**Comment by aldmbmtl** [comment]
This is a known issue with the pagination. I am going to close in favor of https://github.com/juno-fx/mars/issues/44
