### ISSUE TITLE
(Bug: Kuiper) The Monitor was unable to connect to the specified server (deadline-server:8080).

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#282]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

Kuiper

### URL in Hubble.

https://ath.junovfx.com/workstations/

### Browser

Chrome Based

### Describe the bug

Error from Deadline

### To reproduce

No idea! Could be because I launched my script via the file menu and not the juno manager. 

### Screenshots

<img width="785" alt="Screenshot 2024-10-07 at 9 48 10 AM" src="https://github.com/user-attachments/assets/b42ee3b4-8266-4936-a55f-ab24558dd45c">

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Does this block you from using Orion daily?

No

**Comment by aldmbmtl** [comment]
Project is done now and fixed it
