### ISSUE TITLE
(Bug: Kuiper) Nuke doesn't launch

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#283]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

Kuiper

### URL in Hubble.

https://toy.junovfx.com/workstations/

### Browser

Chrome Based

### Describe the bug

Nuke doesn't launch, no error

### To reproduce

Launch nuke

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Does this block you from using Orion daily?

No

**Comment by lamepennies** [comment]
Sorry, just 14 launches but no terminal popup

**Comment by lamepennies** [comment]
Nuke 14 launches but it looks like it's out of the pipeline

**Comment by aldmbmtl** [comment]
Got it, let me check that. I think I know what is causing it.

**Comment by aldmbmtl** [comment]
Got it fixed. @ddesmond this failed because the nuke executable wasn't set by the nuke install on terra. I will take a look at this later.

**Comment by ddesmond** [comment]
> Got it fixed. @ddesmond this failed because the nuke executable wasn't set by the nuke install on terra. I will take a look at this later.

you set it by hand before and the branch is not deployed yet.

**Comment by aldmbmtl** [comment]
Got it :+1:
