### ISSUE TITLE
(Bug: Polaris) Welcome page missing in Polaris

### ISSUE THREAD

**Issue by Mary-dev-prog** [juno-fx/report#284]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

Polaris

### URL in Hubble.

https://ath.junovfx.com/viewer/cecile/

### Browser

Firefox

### Describe the bug

Low prio. 
Firefox bug - File not found  - I am not sure what it should display but it seems to be a welcome page ? 

### To reproduce

Not sure what i am suppose to write here 

### Screenshots

![Screenshot 2024-10-11 at 11 08 16 AM](https://github.com/user-attachments/assets/9e6195a8-8c97-4c25-84a1-88670c7ea619)

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Recent working Orion date

Oct 11

### Does this block you from using Orion daily?

No

**Comment by Mary-dev-prog** [comment]
Not urgent - i am just trying to submit a ticket

**Comment by ddesmond** [comment]
Resolved in latest polaris commits
