### ISSUE TITLE
Actions update

### ISSUE THREAD

**Issue by ddesmond** [juno-fx/report#285]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

all

### Browser

Other

### Describe the bug

https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/

github is changing actions regardin ubuntu.

We probably want to update the actions across the repos?

### To reproduce

https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/

### Regression

No, this bug or issue has existed throughout my experience using Orion

### Does this block you from using Orion daily?

No

**Comment by aldmbmtl** [comment]
Our runners are on base Debian and don't run Ubuntu. These changes are refer to the Github hosted runners which we don't use. The only runner that we use from GitHub is for documentation generation on the Orion docs.
