### ISSUE TITLE
issues create branch feature appears to branch from main not edge

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#31]
When using the create branch feature for our issues, It looks to create the branch from main and not edge. We probably want to change this or have the option to choose.

**Comment by aldmbmtl** [comment]
You have to click the "Change Branch Source" option. It is built in.

![image](https://github.com/juno-fx/report/assets/9037579/b36bb1b4-fe8f-447c-87ed-6c61755d0c1b)
