### ISSUE TITLE
Remove first/last frame from junofile db object

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/report#33]
I think we should look into removing first/last frame as fields on the junofile db object. We are storing this type of info in the metadata dict for all other objects and it seems odd to have it broken out, especially since not all juno files will have a first/last frame. Think of luts and what not.

**Comment by skeleturtle** [comment]
giving this a bump in prio if thats coolio.

**Comment by aldmbmtl** [comment]
This is done
