### ISSUE TITLE
Hubble - Version counts in searches or in general

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#34]
**Is your feature request related to a problem? Please describe.**
It'd be cool to see version counts in searches or in general

**Describe the solution you'd like**
Just add numbers

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
You mean the v{number} that is in the names of the versions?

**Comment by lamepennies** [comment]
Like total versions. Either by task or by show.

**Comment by lamepennies** [comment]
Could be useful for the lists

**Comment by aldmbmtl** [comment]
Got it, this is a lower priority from the task type filtering, but I will jump on that as soon as we free up a bit.

**Comment by aldmbmtl** [comment]
Type filtering has been added in. I will add this to the next round of changes.

https://github.com/juno-fx/report/issues/35

**Comment by aldmbmtl** [comment]
The type filtering is done, I will add the version count in the next round I think.

**Comment by aldmbmtl** [comment]
This is all done for now. Open again if needed
