### ISSUE TITLE
Hubble - Hide task or version types by user

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#35]
**Is your feature request related to a problem? Please describe.**
Be nice to hide certain tasks or versions from a page. Maybe just have a filter setting

**Describe the solution you'd like**
View less stuff if the user doesn't need to view it

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
We can take a look at this. How would it look in the UI? Just a way to set a task to be stuck closed unless manually opened again?

**Comment by lamepennies** [comment]
Yeah just not shown. I guess use case is seeing dozens of lut versions. Those could be hidden.

**Comment by aldmbmtl** [comment]
I am going to start working on this now

**Comment by aldmbmtl** [comment]
This is deployed and only works on tasks/meta objects for now. We can setup version filtering on the next round.

https://github.com/juno-fx/hubble/issues/107

**Comment by aldmbmtl** [comment]
![image](https://github.com/juno-fx/report/assets/9037579/3e140994-2cbd-43a0-8e4b-4d3634d6c5df)
