### ISSUE TITLE
(Bug: hubble) Cannot read properties of null (reading 'email')

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#356]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

hubble

### URL in Hubble.

https://sqm.junovfx.com/workstations/

### Browser

Chrome Based

### Describe the bug

Cannot read properties of null (reading 'email')

### To reproduce

Just trying to log in and seeing this error today. 

### Regression

Yes, this bug started recently or with an X Orion version

### Does this block you from using Orion daily?

Yes

**Comment by aldmbmtl** [comment]
What google account are you using to log in with? It flagged that you tried with your personal gmail. You need to use your juno google account

**Comment by lamepennies** [comment]
It never gave me an option to select one. It just said home or report bug and when I clicked home it didn't take me anywhere

**Comment by aldmbmtl** [comment]
It pulls from your browser. What account are you logged in with on your browser

**Comment by lamepennies** [comment]
I mean I have my usual one but before I had the option to select my google accounts.

**Comment by lamepennies** [comment]
This looks fixed after a reboot. As I told Alex, the homepage didn't take me anywhere or log me out.
