### ISSUE TITLE
Versioning mal function 

### ISSUE THREAD

**Issue by alexander-costa** [juno-fx/report#37]
In the file manager after loading the sequence and submitting to deadline. 
I refreshed the File Manager and my version did not showed up. 

I try the following steps, on each one of them I hit the refresh button
1. Unchecked the "my version" box
2. Unchecked the "my Latest only" box
3. Unchecked "my tasks"

When I looked on the Hubble / My task. I can see the version I rendered 

![image](https://github.com/juno-fx/report/assets/137588482/32fc4d5b-70f7-4367-a13d-6b15e115f4e2)

**Comment by alexander-costa** [comment]
Adding image if the file manager after render was submitted to deadline and completed

![image](https://github.com/juno-fx/report/assets/137588482/59073f4e-c776-4ebb-b16a-af9eaac6600a)

**Comment by oneBlueFish** [comment]
This is loosely related to https://github.com/juno-fx/report/issues/36, see my reponse there for more info.

In the meantime, I will attach a the frames to the version on submission. 

NOTE (regarding this): Loading the file manager will show that there are frames registered to the version, but there is a chance they are still rendering.

**Comment by oneBlueFish** [comment]
![image](https://github.com/juno-fx/report/assets/20176819/4734f0b1-81b3-4f31-b3e1-1d3f07a8c1bc)

This is on edge currently, will need to talk about a few things tomorrow.

**Comment by aldmbmtl** [comment]
This is deployed and working from the looks of it. Please confirm
