### ISSUE TITLE
Batch import plates/versions from search to a contact sheet

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#39]
**Is your feature request related to a problem? Please describe.**
No easy way to bring in batches of plates

**Describe the solution you'd like**
Would love a way to batch import plates/versions from the browser. It'd be great that it also makes a contact sheet and gives you an option to also load in the LUTs under the reads.

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
This is actually a big thing that is needed for evaluating work. @skeleturtle it would be really great to add this to filemanager.

**Comment by skeleturtle** [comment]
When I get back from my camping trip I will look to add this action to our sequences and shot selections in file manager.

However before doing a batch import I will need to update our import logic to organize the actual imports, so we don't just barf nodes all over the place

**Comment by aldmbmtl** [comment]
Sounds good. Let me know if you need any help.

**Comment by skeleturtle** [comment]
![image](https://github.com/juno-fx/report/assets/76455095/f58ba98e-cd7c-4373-b77f-5ef5ef52de85)
![image](https://github.com/juno-fx/report/assets/76455095/7e5c5530-6658-4663-8d97-a4abd7473647)


Initial batch import, and import backdrop organization has been set up. This is currently on our edge branch waiting to be merged to main and released.

Logic for Luts and version batch imports is still needed. Currently this function is only available on the sequence selection. I will look to get a second iteration out soon after.


All imports will utilize our import back drop now for organization. All new nodes imported will be to the far right. Each time import is run the backdrop width is optimized for the number of nodes. So if you move nodes out of the backdrop it will shift the nodes still inside and resize itself to the optimal width. This also will be created during new file.

The backdrop can be deleted, it will simply be recreated on import if it does not already exist.

**Comment by lamepennies** [comment]
This looks awesome. 

If we need to update, we just select the sequence again and a new backdrop will load or will it replace?

**Comment by aldmbmtl** [comment]
It looks like this only brings in the ingests. So not the latest versions for each task. That is probably the next set of things we would need to add. Just for QC.

**Comment by skeleturtle** [comment]
latest update is pending release. Option for task specific batch imports and options to choose whether or not to create a contact sheet
