### ISSUE TITLE
Add read and Viewer inputs in backdrop automatically

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#40]
**Is your feature request related to a problem? Please describe.**
Not really, just want things pretty

**Describe the solution you'd like**
When creating the the nuke scripts, add the plate read and view input to a backdrop for organization

**Describe alternatives you've considered**

**Additional context**

**Comment by skeleturtle** [comment]
This will actually be completed via the update to our imports.

All imports will now be in a neat import backdrop at the top of the script for orginzation.

Future iterations will include sub backdrops for each task.
