### ISSUE TITLE
Add custom frame ranges to shots in Hubble

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#41]
**Is your feature request related to a problem? Please describe.**
Some shots might have different frame ranges than plates provided so we need an option

**Describe the solution you'd like**
Be great to have frame ranges in Hubble and nuke reads that proper work range versus the full range. 

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
This is actually already possible using fields on the shot directly.

![image](https://github.com/juno-fx/report/assets/9037579/924c7119-8c89-4b37-a0b0-99f33fc95b3c)

**Comment by aldmbmtl** [comment]
Feel free to reopen if this doesn't work for you.
