### ISSUE TITLE
Add ability to export vector fields from ViewInput

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Be great to have this ability if we need to compare versions from different shots without double lutting in Nuke.

**Describe alternatives you've considered**

**Additional context**

**Comment by skeleturtle** [comment]
- Set up import action for luts, that doesn't involve it being a viewer input 
- Add batch import lut option. During batch import, if lut option chosen turn off the current shots viewer input

**Comment by skeleturtle** [comment]
Lut import action will now prompt user if they want the lut to be a viewer input or not. Lut filename will also now be set on the nodes label for better visibility. If a lut is imported and is not set to viewer_input I am simply defaulting to "Lut" for the time being.

Still need to add a batch option.

**Comment by skeleturtle** [comment]
Batch option added
