### ISSUE TITLE
Nuke - Clearer text error when trying to add write node in unsaved script

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#45]
**Describe the bug**
Make the error more clearer. It doesn't really say you should save your script before adding a write

**To Reproduce**
Import plate
Add write
Get error

**Expected behavior**
Just better phrasing

**Screenshots**
![Screen Shot 2023-06-26 at 7 47 27 PM](https://github.com/juno-fx/report/assets/84925743/20c2585e-3fac-4202-b377-bf665b674f7f)

**App (please complete the following information):**
Nuke

**Additional context**

**Comment by skeleturtle** [comment]
I updated the message and merged the update into our edge branch.
