### ISSUE TITLE
Have 000 sequence to every show by default

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#46]
**Is your feature request related to a problem? Please describe.**
Just need a way to store show related stuff like cut refs, grain plates, refs 

**Describe the solution you'd like**
Just need a way to store show related stuff like cut refs, grain plates, refs 

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
This would be good for our dev test envs. This should be pretty easy to setup in Luna.

**Comment by aldmbmtl** [comment]
@oneBlueFish has there been any update on this?

**Comment by oneBlueFish** [comment]
This sounds like a good idea, I'll look at adding it

**Comment by aldmbmtl** [comment]
@oneBlueFish can you jump on this after the jfx-luna updates?

**Comment by aldmbmtl** [comment]
This seems to be a duplicate of https://github.com/juno-fx/report/issues/201.

@skeleturtle I am pulling @oneBlueFish off of this so you and I can look at it when we get time.
