### ISSUE TITLE
Ability to publish versions in a different sequence 

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#47]
**Is your feature request related to a problem? Please describe.**
Can't publish versions into a different shot

**Describe the solution you'd like**
Be great to publish grain plates or ref to other sequences (000)

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
@oneBlueFish this is lower prio, but would be good to see if we can set this up

**Comment by skeleturtle** [comment]
I believe this logic is already set up in a way. Users can now save their current scene file into a different context. From there they can do whatever they like with that version. I'm marking as closed unless stated otherwise.
