### ISSUE TITLE
Can't un-assign artists in Hubble

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#49]
**Describe the bug**
I can't un-assign people on tasks/shots in Hubble

**To Reproduce**
Double click on name, remove and save. It'll autofill the previous name. 

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
Hubble

**Additional context**

**Comment by aldmbmtl** [comment]
This is being investigated right now. This is causing hard crashes.

**Comment by aldmbmtl** [comment]
This is fixed and being deployed now.
