### ISSUE TITLE
Can't open previous nuke script

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#50]
**Describe the bug**
Trying to open my previous script and i get this error that it can't find the file

**To Reproduce**
Go to file browser, shot, task, and load script and the error pops up

**Expected behavior**
The script to open.

**Screenshots**

**App (please complete the following information):**
 Nuke

**Additional context**
![Screen Shot 2023-06-27 at 6 43 39 PM](https://github.com/juno-fx/report/assets/84925743/5a4592a1-4aec-4d15-830f-f5f9240ced00)

**Comment by skeleturtle** [comment]
I will take a look. I have not had issues with this functionality, so it makes me wonder if there was a permission issue during the save action. Resulting in the DB entry for the file being made but the file not being properly created.

**Comment by aldmbmtl** [comment]
This was an issue with the shot we deleted. This was the one we ingested again.

**Comment by aldmbmtl** [comment]
This was on us. Sorry about that @lamepennies :(
