### ISSUE TITLE
Install Nuke Survival Toolkit

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#52]
**Is your feature request related to a problem? Please describe.**
Just a great toolset

**Describe the solution you'd like**
Can we install: https://github.com/CreativeLyons/NukeSurvivalToolkit_publicRelease/releases/ 

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
I opened a ticket upstream to contribute back if they are open to it. Otherwise, this is working now.

https://github.com/CreativeLyons/NukeSurvivalToolkit_publicRelease/issues/31
