### ISSUE TITLE
Open Directory

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#56]
It would be nice to add an "Open in directory" option to tasks that have capsules. Meaning, any meta object that has a location on disk, in File Browser I would like to be able to open that capsule with the systems filebrowser just in case we need to debug or manually pull in stuff. Technically, we should never need to do this, but in case of some kind of failure and we need access to the raw storage, it would be nice to have this as a fail safe.

**Comment by skeleturtle** [comment]
A pull request is out for review with Mr. hatfield.

**Comment by skeleturtle** [comment]
this was merged into edge
