### ISSUE TITLE
Mark versions for review in Nuke

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#58]
**Is your feature request related to a problem? Please describe.**
To speed up stuff, it'd be cool to mark a version for review in nuke

**Describe the solution you'd like**
Maybe we could have a Juno tab in the read node or just a drop down that when a node is selected, it'll mark it for review

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
You can actually do this by going to Nuke>Juno>Publish Current Version

![image](https://github.com/juno-fx/report/assets/9037579/72933949-d9db-4d59-91a1-fe6a487c3a9a)


This will change the current versions state to "Publish" and status to "Pending Internal Review"
