### ISSUE TITLE
Add Thumbnails to my tasks in Hubble

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#59]
**Is your feature request related to a problem? Please describe.**
Just to view pretty things

**Describe the solution you'd like**
Add thumbnails in the my tasks in Hubble

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
We can do this actually now. It is just a matter of setting the thumbnail field on the task and Webb will pick it up. This is a @skeleturtle thing in pipeline. We could add that to the publish function mentioned here https://github.com/juno-fx/report/issues/58.
