### ISSUE TITLE
Add shot thumbnail to file browser

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#60]
**Is your feature request related to a problem? Please describe.**
Be cool to see your shot thumbnail in the file browser too

**Describe the solution you'd like**
I was thinking, when you click on a shot, the dog logo goes away for the thumbnail.

**Describe alternatives you've considered**

**Additional context**

**Comment by skeleturtle** [comment]
The shot thumbnail should be showing. If there are issues finding the thumbnail from our Webb service we default to the dog logo. 

Are you not seeing any thumbails?

**Comment by aldmbmtl** [comment]
95D is having an issue finding the frames for the thumbnail for some reason. The rest should be fine.
