### ISSUE TITLE
Number pad on my keyboard doesn't nudge in nuke

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#64]
**Describe the bug**
Can't use my number pad to nudge in nuke or use numbers

**To Reproduce**
My mac number pad to nudge in nuke 

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
Nuke 

**Additional context**

**Comment by aldmbmtl** [comment]
This is actually an upstream issue with NoVNC. I can maybe open a ticket with them. I don't think that is actually something we can fix on our end sadly :(

**Comment by lamepennies** [comment]
Are there any alternatives to nudging in Nuke? If we can't fix this, roto work will be extremely difficult to be accurate unless we get something like Mocha or SFX that uses the arrows.

**Comment by aldmbmtl** [comment]
I can message the Foundry and see.

**Comment by aldmbmtl** [comment]
This is an issue on the NoVNC side. There is no fix for it at the moment :(
