### ISSUE TITLE
Can't log into machine and can't start a new instance

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#65]
**Describe the bug**
Can't log into my machine. It just gave me creating credentials. So I shut it down and tried to make a new machine and I got this new error.

**To Reproduce**
No idea

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**
![Screen Shot 2023-06-28 at 6 55 46 PM](https://github.com/juno-fx/report/assets/84925743/922ccc55-6084-4068-8d69-94224501f749)
![PNG image](https://github.com/juno-fx/report/assets/84925743/c2d36c07-a521-40ce-83fb-9cf0de746185)

**Comment by lamepennies** [comment]
To clarify, this has been working all day until I put in the ticket. Super stable all day.

**Comment by aldmbmtl** [comment]
This is addressed now I think. The patch is deployed so we will see if it breaks again.
