### ISSUE TITLE
Nuke launch error in pipe 1.0.6

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#68]
**Describe the bug**
Can't launch nuke and I don't have a menu.py set up yet so I don't know.
**To Reproduce**
Nuke to launch

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
Pipeline - 1.0.5 and 1.0.6
Nuke X

**Additional context**
![Screen Shot 2023-07-02 at 11 13 40 AM](https://github.com/juno-fx/report/assets/84925743/208b7f41-f4f8-489e-8178-a1f17134cfb1)
![Screen Shot 2023-07-02 at 11 15 59 AM](https://github.com/juno-fx/report/assets/84925743/d6a1f8f3-78cf-420b-a707-ec2d1333f3a4)

**Comment by aldmbmtl** [comment]
This was an upstream issue. Solved by pinning the pydantic version.
