### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#72]
Default with "latest version" unchecked. Artists usually forget to uncheck it and think they lost work. Also, can we have the latest versions ordered on top instead of having to scroll down to find the latest. Would rather have it on the top.

@lamepennies

**Comment by skeleturtle** [comment]
I have a branch kicked up, but am waiting on confirmation about a linting issue before merging into edge.

**Comment by skeleturtle** [comment]
branch is pending review

**Comment by aldmbmtl** [comment]
Looks good. Approved. Merge away
