### ISSUE TITLE
Install pixelfudger toolsets

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#73]
**Is your feature request related to a problem? Please describe.**
Please install pixelfudger toolsets

http://www.pixelfudger.com/

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lamepennies** [comment]
Nevermind, will just add it to my toolsets

**Comment by lamepennies** [comment]
Nevermind, it's a bunch of gizmos

**Comment by aldmbmtl** [comment]
We will need to take these and break them into groups. We can add this to a lower prio for now.
