### ISSUE TITLE
Install Tony's toolsets/gizmos

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#74]
**Is your feature request related to a problem? Please describe.**
Please install the following toolsets and remove any previous ones I've sent you (Laplacian blur I think). Also, if you can install the luma pictures toolsets. 

These also have toolsets from other talented artists I've worked with like Jed Smith that were on his github

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[LumaPictures.zip](https://github.com/juno-fx/report/files/11931501/LumaPictures.zip)
[toolsets.zip](https://github.com/juno-fx/report/files/11931502/toolsets.zip)

**Comment by aldmbmtl** [comment]
I will add these in tomorrow

**Comment by aldmbmtl** [comment]
These are installed

![image](https://github.com/juno-fx/report/assets/9037579/58c91013-92ac-4de6-a96b-70bf6c92d660)
