### ISSUE TITLE
Write Node Precomp

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/report#75]
When a write node is set to write a precomp, can we default the channels to "All" just by default?

**Comment by skeleturtle** [comment]
I can switch this, but if the user then unchecks precomp or chooses matte/slapcomp do we want to default it to something else?

**Comment by skeleturtle** [comment]
added settings for our profiles currently we will have default channels, and file type settings for our profiles.
precomp will default to 'all' channels when checked. When unchecked we will revert back to our current profiles default setting.

This is now on edge

**Comment by aldmbmtl** [comment]
deployed and works great
