### ISSUE TITLE
Application Error when putting in notes in Hubble

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#77]
**Describe the bug**
I get this error when I put notes in:
Application error: a client-side exception has occurred (see the browser console for more information).

**To Reproduce**
Make a note,save it and error

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**

**Comment by lamepennies** [comment]
This randomly got better at some point today, not sure if something was pushed.

**Comment by aldmbmtl** [comment]
This was fixed in the latest release that was just rolled out 30 mins ago.
