### ISSUE TITLE
Note Formatting

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#78]
**Is your feature request related to a problem? Please describe.**
Add note formatting
**Describe the solution you'd like**
Would love for a note to look like this:

Looks terrible
1. Too many pixels
2. Why so smudgy?
3. This color doesn't give off enough "pixel" for me

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
Maybe @Anthonygen1 can help out with this when Atlas is in a good spot.

**Comment by aldmbmtl** [comment]
This is fixed in the latest Hubble :)
