### ISSUE TITLE
Install Darktable (lightroom alternative)

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#8]
**Is your feature request related to a problem? Please describe.**
I think we'll need a photo developer software like Darkroom at some point.
https://www.darktable.org/2022/12/darktable-4.2.0-released/

**Describe the solution you'd like**
Install this whenever, it's free

**Describe alternatives you've considered**
I'll be making tickets for the other free software

**Comment by aldmbmtl** [comment]
Holding on this. Workstations are getting quite large so I need to find a portable version that I can install on a share instead.
