### ISSUE TITLE
Internal Session Error on Sophia

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#80]
**Describe the bug**
Got an error called internal session error on Sophia

**To Reproduce**

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**
![Screen Shot 2023-07-03 at 5 22 14 PM](https://github.com/juno-fx/report/assets/84925743/f14a856f-6c9c-4b71-baca-76fa579c42e4)

**Comment by lamepennies** [comment]
I left it on if you want to connect. Starting another machine.

**Comment by aldmbmtl** [comment]
This was a misconfiguration on the kubernetes nodes. This is fixed now.
