### ISSUE TITLE
File Manager as a Nuke Pane?

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#82]
**Is your feature request related to a problem? Please describe.**
Could this be a panel by chance?

**Describe the solution you'd like**
Would like to make it a panel we can add if we wanted.

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
This is a pipeline thing that should be doable

**Comment by skeleturtle** [comment]
This is updated and merged into edge. We are currently pending release.
