### ISSUE TITLE
Filter versions by multiple status types

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#83]
**Is your feature request related to a problem? Please describe.**
Be great to filter based on multiple status types

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
I will probably need to do the same think with this that I did with the type filtering. Maybe I will make a filter bar instead of putting it on the top of the table.

**Comment by aldmbmtl** [comment]
This is addressed in the latest hubbles grouping functionality :)
