### ISSUE TITLE
Add refresh to tasks/versions pages

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#85]
**Is your feature request related to a problem? Please describe.**
Add a refresh button so you don't need to reload the whole page and to refresh what you need.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
Ha! I literally just deployed this last night

![image](https://github.com/juno-fx/report/assets/9037579/704adf78-e451-440b-b8d0-967e0e9fe133)
