### ISSUE TITLE
Filtering in versions page isn't filtering properly

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#86]
**Describe the bug**
When I filter the versions page to anything, it ends up showing all versions.

**To Reproduce**
Needs to just show the versions statuses of what is selected to be filtered.

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**
![Screen Shot 2023-07-04 at 12 47 30 PM](https://github.com/juno-fx/report/assets/84925743/1bd5bb79-cd5c-4bfe-8d58-99be78ba51a8)

**Comment by aldmbmtl** [comment]
This is working now properly
