### ISSUE TITLE
Wiki/Bookshelf 

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#88]
**Is your feature request related to a problem? Please describe.**
Would love to get a wiki going with processes, docs, workflows, yada yada.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aldmbmtl** [comment]
The dev team has one of these internally (it is super out of date), but I can see about setting one up for the artist team.

**Comment by aldmbmtl** [comment]
Got this set up :)

https://wiki.hatfieldfx.com/
