### ISSUE TITLE
Install GIMP

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#9]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, just a feature request

**Describe the solution you'd like**
Would like this installed:
https://www.gimp.org

It's a good photoshop alternative
**Describe alternatives you've considered**
Making other tickets for alternative software

**Comment by aldmbmtl** [comment]
Holding on this. Workstations are getting quite large so I need to find a portable version that I can install on a share instead.
