### ISSUE TITLE
Nuke crashes

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#90]
**Describe the bug**
Nuke crashes in 1.0.8
**To Reproduce**

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**

**Comment by aldmbmtl** [comment]
What does the terminal kick back? I have been running it this morning with no issues. Seg fault?

**Comment by lamepennies** [comment]
I think. It crashed when it opened and then it crashed again after I loaded the asset manager. I just went to 1.0.7

**Comment by aldmbmtl** [comment]
Ok, I will take a look later today. For now, just stick with the roll back.

**Comment by aldmbmtl** [comment]
We are starting to zero in on the issue. Looks to be a spam call being made but one of our client libraries. This is cropping up because of the size of the project data. We are working on it now.

**Comment by aldmbmtl** [comment]
This seems to be fixed
