### ISSUE TITLE
Artists can publish plates after they are already ingested

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#91]
**Describe the bug**
Artist can publish plates versus it being locked. Just a flag as i know we're still working on permission issues.

**To Reproduce**

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**

**Comment by aldmbmtl** [comment]
I am not sure I understand the issue.

**Comment by skeleturtle** [comment]
I also do not fully understand, currently users can't create new files from a ingest task.

Lets chat in the next meeting.

**Comment by lamepennies** [comment]
I saw 2 versions of a plate publish on a shot when I put this in. We can close it, i should've put what shot it was.
