### ISSUE TITLE
Submit to deadline doesn't work

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#93]
**Describe the bug**
Hello, when I try to submit a job to deadline, it doesn't do anything. It's been about 5 minutes after click and nothing has happened.

**To Reproduce**
Make a write, adjust settings, and click submit to deadline. I can drag the window around so it's not frozen. 

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
Pipeline 1.0.9

**Additional context**
![Screen Shot 2023-07-08 at 1 59 21 PM](https://github.com/juno-fx/report/assets/84925743/ca5f0378-6219-47b4-abeb-c55442eed001)

**Comment by aldmbmtl** [comment]
This was due to the redis cache issue. This has been fixed
