### ISSUE TITLE
File Browser - If you select a version, you can't create new file

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/report#94]
**Describe the bug**
Noticed when I try to make a new version from scratch and I have a version selected, I can't create a new file. I need to click away from the task to something new and back to have the button pop up.
**To Reproduce**
Select a task then version, no option appears to create new version, click away on to another task and back without clicking on a version and you can create a new file. 

**Expected behavior**

**Screenshots**

**App (please complete the following information):**
 - Pipeline Version: [e.g. v1.0.0]
 - Application: [e.g. Nuke]
 - Tool: [e.g. File Browser]

**Additional context**

**Comment by skeleturtle** [comment]
![image](https://github.com/juno-fx/report/assets/76455095/1f7810e2-68fa-4a83-875c-4675c1e5abba)


adding ability to create a new file from the selected version. This will do a nuke.NodePaste() from the selected versions nuke junoFile.

**Comment by skeleturtle** [comment]
This has been pushed to our edge branch and is awaiting merge to Main/release
